######################################################
# TODO: Use this secrets storing technique for other repos
######################################################
#
# Ref: https://www.programonaut.com/how-to-deploy-a-git-repository-to-a-server-using-github-actions/
#
# 1. Go to “Settings > Secrets > Actions”
# 2. Create the following secrets:
#
# SSH_PRIVATE_KEY: content of the private key file
# SSH_USER: user to access the server
# SSH_HOST: hostname/ip-address of your server
# WORK_DIR: path to the directory containing the repository
# MAIN_BRANCH: name of the main branch (mostly main)

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy_prod:
    name: deploy_prod
    runs-on: ubuntu-latest    # is this needed?
    environment: prod

    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: deploy via kubernetes
      run: |
        ssh -T ${{ vars.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          cd ${{ vars.WORK_DIR }}
          git checkout ${{ vars.MAIN_BRANCH || 'prod' }}
          git pull
          kubectl create configmap haproxy-config --from-file=haproxy.cfg=haproxy.cfg --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f ./k3s/routing_haproxy_deployment.yaml
          kubectl rollout restart deployment routing-haproxy
        EOF
    - name: cleanup
      run: rm -rf ~/.ssh

# To undo deployment
# kubectl rollout undo deployment/routing-haproxy